[project]
name = "dcd-lago"
version = "1.0.4"
description = "Python implementation of the LAGO method..."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [
    { name="Victor Brabant", email="victorbrabant@gmail.com" }
]
keywords = ["lago", "networks", "temporal networks", "modularity"]
[project.urls]
Homepage = "https://github.com/fondationsahar/dynamic_community_detection"
Issues = "https://github.com/fondationsahar/dynamic_community_detection/issues"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["lago*"]
